import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NgControl } from '@angular/forms';
import { tamanhoInputType, tipoTextoFeedBackType } from '../../types/inputTypes';
import { TamanhoInputEnum } from '../../enum/inputEnums';
import * as ɵngcc0 from '@angular/core';
export declare class DscInputComponent implements OnInit, OnChanges, AfterViewInit, ControlValueAccessor {
    controlDir: NgControl;
    dscRotulo?: string;
    dscRotulo_?: string;
    dscInformacaoAdicional?: string;
    dscInformacaoAdicional_?: string;
    dscIconeInformativo?: string;
    dscIconeInformativo_?: string;
    dscIconLeft?: string;
    dscIconLeft_?: string;
    dscPlaceholder: string;
    dscPlaceholder_: string;
    dscIsClearButton?: boolean;
    dscIsClearButton_: boolean;
    dscTipoTextoFeedBack?: tipoTextoFeedBackType;
    dscTipoTextoFeedBack_: tipoTextoFeedBackType;
    dscTextoFeedBack?: string;
    dscTextoFeedBack_: string;
    dscTextoComplementar?: string;
    dscTextoComplementar_?: string;
    dscIsContadorCaractere?: boolean;
    dscIsContadorCaractere_: boolean;
    dscTamanhoMaximo?: number;
    dscTamanhoMaximo_: number;
    dscMask?: any;
    dscMask_: any;
    dscIsPassword?: boolean;
    dscIsPassword_: boolean;
    dscVoice?: boolean;
    dscVoice_: boolean;
    dscTipoTamanhoInput: tamanhoInputType;
    dscTipoTamanhoInput_: TamanhoInputEnum;
    dscEventEnter: EventEmitter<void>;
    input: ElementRef;
    classeBox: string;
    arrayType: string[];
    iconeFeedBack: string;
    mapaClasseIcone: Map<string, string>;
    typeDomInput: string;
    showMicIcon: boolean;
    mapaTamanhoInput: Map<TamanhoInputEnum, string>;
    mapaHeader: Map<TamanhoInputEnum, string>;
    classeHeader: string;
    classFormField: string;
    classComplementar: string;
    stackSuffix: any[];
    disabled: boolean;
    onChange: (_value: any) => void;
    onTouched: () => void;
    constructor(controlDir: NgControl);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    registerOnChange(fn: (value: any) => void): void;
    setDisabledState(disabled: boolean): void;
    writeValue(value: any): void;
    registerOnTouched(fn: () => void): void;
    aplicarClasseFeedBack(): void;
    aplicarClasseComplementar(): void;
    aplicarClasseMatFormField(): void;
    limparInput(): void;
    inicializarMapaIconeFeedback(): void;
    private aplicarMascara;
    private limparMascara;
    private validarPassword;
    private configurarInputMask;
    escutarTeclas($event: KeyboardEvent): void;
    private tratarMicrofone;
    private hideMic;
    private showMic;
    validarSuffix(): void;
    retornarSuffixMarcado(): void;
    inicializarMapaTamanhoInput(): void;
    inicializarMapaHeader(): void;
    mudarClasseParaMic(): void;
    isInvalid(): boolean;
    private tratarClasseMatFormFieldClearButton;
    static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<DscInputComponent, [{ self: true; }]>;
    static ɵcmp: ɵngcc0.ɵɵComponentDeclaration<DscInputComponent, "dsc-input", never, { "dscTipoTamanhoInput": "dscTipoTamanhoInput"; "dscRotulo": "dscRotulo"; "dscInformacaoAdicional": "dscInformacaoAdicional"; "dscIconeInformativo": "dscIconeInformativo"; "dscIconLeft": "dscIconLeft"; "dscPlaceholder": "dscPlaceholder"; "dscIsClearButton": "dscIsClearButton"; "dscTipoTextoFeedBack": "dscTipoTextoFeedBack"; "dscTextoFeedBack": "dscTextoFeedBack"; "dscTextoComplementar": "dscTextoComplementar"; "dscIsContadorCaractere": "dscIsContadorCaractere"; "dscTamanhoMaximo": "dscTamanhoMaximo"; "dscMask": "dscMask"; "dscIsPassword": "dscIsPassword"; "dscVoice": "dscVoice"; }, { "dscEventEnter": "dscEventEnter"; }, never, never>;
}

//# sourceMappingURL=dsc-input.component.d.ts.map